---
name: frontend-ci

on:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  test-build:
    name: Build
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version-file: frontend/.node-version
          cache: npm

      - name: Install Dependencies
        id: npm-ci
        run: npm ci

      - name: build
        id: npm-build
        run: npm run build
